version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/app
    links:
      - mailcatcher

  database:
    image: postgres:11.6
    env_file:
      - .env/development/database
    volumes:
      - babywearing_pg:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - .env/development/web
    ports:
      - "8080:8080"
    links:
      - app

volumes:
  babywearing_pg:
